### ISSUE TITLE
Unstructured file loader allowing pageContent to be undefined

### ISSUE THREAD

**Issue by simon-fernandes** [hwchase17/langchainjs#2144]
I've noticed that sometimes a `Document` returned by the `Unstructured` file loader will have an undefined `pageContent` property.

![image](https://github.com/hwchase17/langchainjs/assets/47521318/318f7090-6db3-4062-b4cf-aa742cb896e7)

As a result, when being passed to `OpenAiEmbeddings` `embedDocuments()`, the `replace()` call fails as the passed texts property will be `undefined`.

![image](https://github.com/hwchase17/langchainjs/assets/47521318/89dd00d9-6d2b-4f87-8104-6a6402f411e8)

Could this be fixed by either:

1. Preventing the loaders from building an `undefined` `pageContent` property in the first place? Is there any valid use case for having `pageContent` as `undefined`?
2. Checking each `texts` isn't `undefined` before trying to call `replace()` on them within `OpenAiEmbeddings` `embedDocuments()`

Thanks!

**Comment by jacoblee93** [comment]
Oof, yeah this should never be the case. Option 1 is the better approach here - are you up for opening a PR that filters out any content-less docs?

**Comment by simon-fernandes** [comment]
> Oof, yeah this should never be the case. Option 1 is the better approach here - are you up for opening a PR that filters out any content-less docs?

I've linked a fairly straight forward PR that should fix the issue. First PR ever to an open source project!

**Comment by ktalebian** [comment]
@simon-fernandes this issue is back with the `@langchain/community` version. I made a quick PR to fix it https://github.com/langchain-ai/langchainjs/pull/6532
